# site settings
title: DEVREAL
header_title: DEVREAL Tech Conversations
subtitle: Tech Conversations
cover-image: https://cdn.svenmalvik.com/images/devreal-di-cover-full.jpg
email: sven@malvik.de
form-link: https://forms.office.com/Pages/ResponsePage.aspx?id=DQSIkWdsW0yxEjajBLZtrQAAAAAAAAAAAANAAQFTWSZUOTNCUjkzRzJIMzhRNDJKVkVTNkxIWEhZUy4u
description: "How are organizations like Vipps, Microsoft, Tata Consultancy Services (TCS) and Aker Solutions establishing a diverse and inclusive workplace? What initiatives are they driving and how can we all work together to create a positive impact?"
baseurl: ""
url: 
author: Sven Malvik
street_address: Trettåsen 50
city: Fjerdingby
state: 
zip_code: 2008
country: Norway
phone: (+47) 948 225 79

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6
reserve_btn: "Reserve Free Seat"
apimnolink_btn: "Read or Watch Now"
apimnolink: https://www.svenmalvik.com/azure-apim-at-norway/

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: https://www.linkedin.com/in/svenmalvik
pinterest_url:
slack_url:
twitter_url:

markdown: kramdown

sass:
  style: compressed
